### ISSUE TITLE
interpreting column names 

### ISSUE THREAD

**Issue by Huanle** [a-slide/NanopolishComp#21]
Hi @a-slide ,
Thanks a lot for developing this program.
Can you offer some detailed intepretation of the column names?
**ref_pos ref_kmer        num_events      dwell_time      NNNNN_dwell_time        mismatch_dwell_time     start_idx       end_idx      mean    median  num_signals     samples**

It seems nanopolish can associate multiple events to the same ref-read kmer. Right?

**Comment by a-slide** [comment]
Hi @Huanle 

The meaning of the columns is detailed in the documentation:
https://a-slide.github.io/NanopolishComp/demo/Eventalign_collapse_usage/#output-files-format

And yes the whole point of Eventalign_collapse is to collapse events from the output of Nanopolish to their corresponding kmers. In addition, the index file collapses information at the read level.

Best

**Comment by Huanle** [comment]
thanks @a-slide .
Are the **mean**s in the collapsed results the mean of **event_level_mean** from nanopolish eventalign resutls?

**Comment by a-slide** [comment]
No it is the mean of the raw intensities values, otherwise it would not be correct. You could always get away by computing a weighted mean but it is not as precise. 
As indicated in the doc, it is available only if nanopolish eventalign was ran with --samples option.

**Comment by Huanle** [comment]
@a-slide thanks heaps for clarifying this.

**Comment by a-slide** [comment]
You are welcome
