### ISSUE TITLE
NanopolishComp on empty files

### ISSUE THREAD

**Issue by tleonardi** [a-slide/NanopolishComp#8]
Running NanopolishComp on a Nanopolish file that only contains the header line causes it to throw an exception and to hand indefinitely:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nanopore/.local/lib/python3.6/site-packages/NanopolishComp/Eventalign_collapse.py", line 112, in _split_reads
    read_id=ls[read_id_idx]
IndexError: list index out of range
```

I think the solution might be a try: block on line 111-115 of Eventalign_collapse.py.
https://github.com/a-slide/NanopolishComp/blob/6eaa5d5f1ebd73353890830512a281513bf3082b/NanopolishComp/Eventalign_collapse.py#L111-L115

**Comment by a-slide** [comment]
Fixed. Multiprocessing error handling is not that  simple.
I had to create a error queue that is monitored between processes start and join.
Any error encountered in a child process is enqueued and get raised in the main body immediately and all processes are killed silently.
At the end of the day, the hack is pretty simple. I should implement it in other program as well.

**Comment by tleonardi** [comment]
Cool, thanks for looking into this!
Might be useful for me as well in the future ;)
